# Generated by Django 5.1.2 on 2024-11-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='expertise',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
