# Generated by Django 5.1.2 on 2025-01-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faulttype',
            name='importances',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
