# Generated by Django 5.1.3 on 2025-02-27 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tasks', '0001_initial'),
        ('authentication', '0001_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reports.report'),
        ),
        migrations.AddField(
            model_name='task',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.technician'),
        ),
    ]
