# Generated by Django 5.1.3 on 2025-03-08 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('paused', 'Paused'), ('failed', 'Failed'), ('complete', 'Complete')], default='In Progress', max_length=20),
        ),
    ]
